site_name: Note
site_description: Where I write what I want to write
site_author: lhwdev
site_url: http://lhwdev.github.io/note
repo_url: https://github.com/lhwdev/note
copyright: Copyright &copy; lhwdev 2021. See <a href="https://github.com/lhwdev/note/tree/master/LICENSE">License</a>.

extra_javascript: []
extra_css: []
dev_addr: localhost:8000

plugins:
  - minify:
      minify_html: true

theme:
  name: material
  custom_dir: theme_override
  palette:
    scheme: preference
    primary: indigo
    accent: indigo

markdown_extensions:
  - pymdownx.highlight:
      use_pygments: true
  - pymdownx.inlinehilite
  - admonition
  - pymdownx.superfences

nav:
  - Home: index.md
  - Jetpack compose:
    - compose/how-it-works.md
