site_name: Note
site_description: Where I write what I want to write
site_author: lhwdev
site_url: http://lhwdev.github.io/note
repo_url: https://github.com/lhwdev/note
copyright: Copyright &copy; lhwdev 2021. See <a href="https://github.com/lhwdev/note/tree/master/LICENSE">License</a>.

extra_javascript: []
extra_css: []
dev_addr: localhost:8000

plugins:
  - search
  - minify:
      minify_html: true
  - macros:
      module_name: macros/main

theme:
  name: material
  custom_dir: theme_override
  palette:
    scheme: preference
    primary: indigo
    accent: indigo
  features:
    - navigation.instant

markdown_extensions:
  - pymdownx.highlight:
      use_pygments: true
  - pymdownx.tilde
  - pymdownx.inlinehilite
  - admonition
  - pymdownx.superfences
  - meta
  - toc:
      permalink: true

nav:
  - index.md
  - making.md
  - debug-page.md
  - 고등학교 개발:
    - high/covid-selftest-macro.md
  - Kotlin Compiler Plugin:
    - kotlin-compiler-plugin/backend-ir.md
  - Jetpack compose:
    - compose/how-it-works.md
  - Other:
    - other/windows-self-driver-signing.md

