name: Deploy page
on:
  push:
    branches:
      - master
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    container: squidfunk/mkdocs-material
    steps:
      - uses: actions/checkout@v2
      - run: |
          pip install mkdocs-macros-plugin
          pip install mdx_del_int
      - run: mkdocs gh-deploy --force
